#    Postgresql database.yml file
common: &common
  adapter: postgresql
  #username: 'berliblog'
  #password: 'berliblog'
  username: postgres
  password: Lullaby
  host: localhost
  pool: 5

development:
  <<: *common
  database: easy_plan_development

test:
  <<: *common
  database: easy_plan_test

production:
  <<: *common
  database: easy_plan_production
